// Code generated by hertz generator.

package main

import (
	handler "lintang/go_hertz_template/biz/handler"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// go func() {
		
	// }()

	// // your code ...
}
