// Code generated by Kitex v0.9.1. DO NOT EDIT.
package helloservice

import (
	server "github.com/cloudwego/kitex/server"
	pb "lintang/go_hertz_template/kitex_gen/go_hertz_template_lintang/pb"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler pb.HelloService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler pb.HelloService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
