// Code generated by hertz generator.

package hello

import (
	"context"

	hello "lintang/go_hertz_template/biz/model/basic/hello"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Method1 .
// @router /helloLintang [GET]
func Method1(ctx context.Context, c *app.RequestContext) {
	var err error
	var req hello.HelloReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(hello.HelloResp)

	resp.RespBody = "hello, " + req.Name

	c.JSON(consts.StatusOK, resp)
}
